spring.application.name=kilimochain

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/kilimochain
spring.datasource.username=postgres
spring.datasource.password=Damaris

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional but recommended
spring.jpa.open-in-view=false

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=bXktc3VwZXItc2VjdXJlLWtleS1mb3Ita2lsaW1vLWNoYWluLTIwMjYtand0LXRva2Vu
jwt.expiration-ms=86400000

# ===============================
# LOGGING (optional)
# ===============================
logging.level.org.springframework.security=DEBUG